name: Testing Github API

on:
  push:
    branches: [ "PK-85-github-ci" ]
        
env:
  GODOT_VERSION: 3.5.1
  EXPORT_NAME: "${{ github.event.repository.name }}-debug"
  PROJECT_PATH: "./YourNotAlone"

jobs:
  export:
    name: Testing Github API
    runs-on: ubuntu-latest
    steps:
      - name: Find Old Artifacts
        uses: actions/github-script@v6
        id: find-artifacts
        with:
          script: |
            const res = await github.rest.actions.listArtifactsForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
            })

            return res.data.artifacts
                   .sort({a,b} => (new Date(a.created_at)) - (new Date(b.created_at)))
      - name: Print found artifacts
        run: echo "${{steps.find-artifacts.outputs.result}}"
    

